src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ApiResource(
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}}
 * )
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà utilisé")
 * @UniqueEntity(fields={"pseudo"}, message="Ce pseudo est déjà utilisé")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups({"read", "write"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Groups({"write"})
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=45, unique=true)
     * @Groups({"read", "write"})
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"read", "write"})
     */
    private $bio;

    /**
     * @ORM\Column(type="date")
     * @Groups({"read", "write"})
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="author", orphanRemoval=true)
     * @Groups({"read"})
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=Retweet::class, mappedBy="author", orphanRemoval=true)
     * @Groups({"read"})
     */
    private $retweets;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     * @Groups({"read"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=MessageLike::class, mappedBy="author", orphanRemoval=true)
     * @Groups({"read"})
     */
    private $messageLikes;

    /**
     * @ORM\OneToMany(targetEntity=CommentLike::class, mappedBy="author", orphanRemoval=true)
     * @Groups({"read"})
     */
    private $commentLikes;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"read"})
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     * @Groups({"read", "write"})
     */
    private $avatarName;

    /**
     * @Vich\UploadableField(mapping="avatars", fileNameProperty="avatarName")
     * @var File|null
     * @Groups({"read", "write"})
     */
    private $avatarFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTimeInterface|null
     * @Groups({"read", "write"})
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Follow::class, mappedBy="follow_target", orphanRemoval=true, cascade={"persist"})
     * @Groups({"read"})
     */
    private $followers;

    /**
     * @ORM\OneToMany(targetEntity=Follow::class, mappedBy="follow_source", orphanRemoval=true, cascade={"persist"})
     * @Groups({"read"})
     */
    private $followings;

    /**
     * @ORM\OneToMany(targetEntity=Report::class, mappedBy="userid")
     */
    private $reports;

    /**
     * @ORM\OneToMany(targetEntity=ContactModerator::class, mappedBy="author", orphanRemoval=true)
     */
    private $contactModerators;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->retweets = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->messageLikes = new ArrayCollection();
        $this->commentLikes = new ArrayCollection();
        $this->followers = new ArrayCollection();
        $this->followings = new ArrayCollection();
        $this->reports = new ArrayCollection();
        $this->contactModerators = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setAuthor($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getAuthor() === $this) {
                $message->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Retweet[]
     */
    public function getRetweets(): Collection
    {
        return $this->retweets;
    }

    public function addRetweet(Retweet $retweet): self
    {
        if (!$this->retweets->contains($retweet)) {
            $this->retweets[] = $retweet;
            $retweet->setAuthor($this);
        }

        return $this;
    }

    public function removeRetweet(Retweet $retweet): self
    {
        if ($this->retweets->removeElement($retweet)) {
            // set the owning side to null (unless already changed)
            if ($retweet->getAuthor() === $this) {
                $retweet->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MessageLike[]
     */
    public function getMessageLikes(): Collection
    {
        return $this->messageLikes;
    }

    public function addMessageLike(MessageLike $messageLike): self
    {
        if (!$this->messageLikes->contains($messageLike)) {
            $this->messageLikes[] = $messageLike;
            $messageLike->setAuthor($this);
        }

        return $this;
    }

    public function removeMessageLike(MessageLike $messageLike): self
    {
        if ($this->messageLikes->removeElement($messageLike)) {
            // set the owning side to null (unless already changed)
            if ($messageLike->getAuthor() === $this) {
                $messageLike->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CommentLike[]
     */
    public function getCommentLikes(): Collection
    {
        return $this->commentLikes;
    }

    public function addCommentLike(CommentLike $commentLike): self
    {
        if (!$this->commentLikes->contains($commentLike)) {
            $this->commentLikes[] = $commentLike;
            $commentLike->setAuthor($this);
        }

        return $this;
    }

    public function removeCommentLike(CommentLike $commentLike): self
    {
        if ($this->commentLikes->removeElement($commentLike)) {
            // set the owning side to null (unless already changed)
            if ($commentLike->getAuthor() === $this) {

templates/profil/_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} — {{ 'profile.edit'|trans }} — {{ app.user.pseudo }}{% endblock %}
{% block body %}
    {% for flashError in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}

    <div id="profile_editor">
        {{ form_start(form, {'attr': {'data-id': app.user.id}}) }}

        <div class="mx-auto mt-5" style="width: 100px; height: 100px">
            {{ include('icons/canari.html.twig') }}
        </div>

        <h3 class="text-center mt-5 mb-4 connexion_header">{{ 'profile.edit'|trans }}</h3>

        <div class=" edit-profil-form">

            {{ form_row(form.pseudo)}}
            {{ form_row(form.bio) }}
            {{ form_row(form.plainPassword) }}
            {{ form_row(form.avatarFile) }}
            <div class="d-flex justify-content-center align-items-center flex-column" id="avatar_block">
                <div class="my-3" id="preview_profile_avatar"></div>
                <button type="button" class="btn btn-primary" id="refreshAvatar" style="display: none">Supprimer l'avatar</button>
            </div>

            <button type="submit" class="btn btn-primary connexion_button w-100 my-5 font-weight-bold">{{ 'edit.label'|trans }}</button>

        </div>

        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('edit-profile') }}
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}G@zouiller —
    {% if user is same as app.user %}
        {{ 'profile.link'|trans }}
    {% else %}
        {{ 'profile.title'|trans }} {{ user.pseudo }}
    {% endif %}
{% endblock %}

{% block body %}
    <main class="container d-flex justify-content-center my-5 flex-column" id="main_profile">
        <div class="btn-group">
            {# DELETE ACCOUNT #}
            {% if is_granted('ROLE_ADMIN') %}
                <div class="delete-container mr-1">
                    <div class="delete-content">
                        <button type="button" class="btn btn-danger font-weight-bold" id="btn-delete">{{ 'account_delete'|trans }}</button>
                    </div>
                </div>
            {% endif %}
            {% if is_granted('ROLE_USER') %}
                <div class="signal-container text-right mr-1">
                    <div class="signal-content">
                        <a type="button" class="btn btn-warning font-weight-bold" id="btn-signal" href="{{ path('report', {type: 'user', id: user.id}) }}">Signaler le compte</a>
                    </div>
                </div>
            {% endif %}
        </div>

        <section class="card-profile mx-auto my-2 w-100">
            <div class="card-profile-container p-2">
                <div class="card-profile-content">
                    <!-- PROFILE CARD HEADER -->
                    <section class="card-profile-header">
                        <!-- AVATAR -->
                        <div class="d-flex justify-content-center align-items-center text-center">
                            <div class="avatar-body">
                                {% if user.avatarName is not same as null %}
                                    <img id="user-avatar" class="image-avatar rounded-circle" src="{{ vich_uploader_asset(user, 'avatarFile') }}" alt="{{ user.avatarName }}">
                                {% else %}
                                    <span class="placeholder-avatar rounded-circle d-flex justify-content-center align-items-center"><span>{{ user.pseudo|first }}</span></span>
                                {% endif %}
                            </div>
                            <div class="ml-2 d-flex flex-column justify-content-center">
                                <h3 id="user-pseudo" class="subscriber-author text-primary text-left">@{{ user.pseudo }}</h3>
                                <p id="user-since">{{ 'joined'|trans({'date': user.createdAt|date('date_format'|trans)}) }}</p>
                            </div>
                        </div>

                        <!-- PSEUDO -->
                        {% if user is same as app.user %}
                            <div class="edit-profile mt-2 d-flex justify-content-center flex-row">
                                <a href="{{ path('name_myProfileUpdate') }}" class="mr-2 my-2 edit_link">
                                    <svg height="24" viewBox="0 -1 401.52289 401" width="24" xmlns="http://www.w3.org/2000/svg"><path fill="#fff" d="m370.589844 250.972656c-5.523438 0-10 4.476563-10 10v88.789063c-.019532 16.5625-13.4375 29.984375-30 30h-280.589844c-16.5625-.015625-29.980469-13.4375-30-30v-260.589844c.019531-16.558594 13.4375-29.980469 30-30h88.789062c5.523438 0 10-4.476563 10-10 0-5.519531-4.476562-10-10-10h-88.789062c-27.601562.03125-49.96875 22.398437-50 50v260.59375c.03125 27.601563 22.398438 49.96875 50 50h280.589844c27.601562-.03125 49.96875-22.398437 50-50v-88.792969c0-5.523437-4.476563-10-10-10zm0 0"/><path fill="#fff" d="m376.628906 13.441406c-17.574218-17.574218-46.066406-17.574218-63.640625 0l-178.40625 178.40625c-1.222656 1.222656-2.105469 2.738282-2.566406 4.402344l-23.460937 84.699219c-.964844 3.472656.015624 7.191406 2.5625 9.742187 2.550781 2.546875 6.269531 3.527344 9.742187 2.566406l84.699219-23.464843c1.664062-.460938 3.179687-1.34375 4.402344-2.566407l178.402343-178.410156c17.546875-17.585937 17.546875-46.054687 0-63.640625zm-220.257812 184.90625 146.011718-146.015625 47.089844 47.089844-146.015625 146.015625zm-9.40625 18.875 37.621094 37.625-52.039063 14.417969zm227.257812-142.546875-10.605468 10.605469-47.09375-47.09375 10.609374-10.605469c9.761719-9.761719 25.589844-9.761719 35.351563 0l11.738281 11.734375c9.746094 9.773438 9.746094 25.589844 0 35.359375zm0 0"/></svg>
                                    {{ 'profile.edit'|trans }}
                                </a>
                            </div>
                        {% endif %}

                        <!-- FOLLOWS & FOLLOWERS COUNT -->
                        <section class="my-2 mx-auto text-center">
                            <div class="followers-container d-inline-block mx-3">
                                <span class="follower-nb text-primary font-weight-bold">{{ user.followers|length }}</span><p>{{ 'num_followers'|trans({'number':user.followers|length}) }}</p>
                            </div>
                            <div class="following-container d-inline-block mx-3">
                                <span class="following-nb text-primary font-weight-bold">{{ user.followings|length }}</span><p>{{ 'num_followings'|trans({'number':user.followings|length}) }}</p>
                            </div>
                        </section>

                        <!-- BIO -->
                        <section class="btn-tweet pt-3 mt-2 mb-4 text-center">
                            <p class="text-white" id="bio">{{ user.bio }}</p>
                        </section>
                    </section>

                    <!-- FOLLOW & FOLLOWERS ACCORDION -->
                    <hr class="border-white w-50 my-5">
                    <section id="accordion">

                        <!-- FOLLOWING BUTTON -->
                        <section class="card">
                            <div class="card-header text-center" id="headingFollowing">
                                <h5 class="mb-0">
                                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFollowing" aria-expanded="true" aria-controls="collapseOne">
                                        {{ 'followings'|trans }}
                                    </button>
                                </h5>
                            </div>

                            <!-- FOLLOWING CONTENT -->
                            <div id="collapseFollowing" class="collapse" aria-labelledby="headingFollowing" data-parent="#accordion">
                                <div class="card-body" id="following_cards">
                                    {# FOLLOWING CARDS GOES HERE #}
                                </div>
                            </div>
                        </section>

                        <!-- FOLLOWERS BUTTON -->
                        <section class="card">
                            <div class="card-header text-center" id="headingFollowers">
                                <h5 class="mb-0">
                                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFollowers" aria-expanded="false" aria-controls="collapseTwo">
                                        {{ 'followers'|trans }}
                                    </button>
                                </h5>
                            </div>

                            <!-- FOLLOWERS CONTENT -->
                            <div id="collapseFollowers" class="collapse" aria-labelledby="headingFollowers" data-parent="#accordion">
                                <div class="card-body" id="follower_cards">
                                    {#  FOLLOWER CARDS GOES HERE #}
                                </div>
                            </div>
                        </section>
                    </section>

                    <!-- TWEET SHORTCUT -->
                    {% if user is same as app.user %}
                        <hr class="border-white w-50 my-5">
                        <section>
                            {{ include('message/_form.html.twig') }}
                        </section>
                    {% endif %}

                    {# TWEETS #}
                    <hr class="border-white w-50 my-5">
                    <section class="container-lg d-flex justify-content-center flex-column" id="message-container"
                            {% if is_granted('ROLE_USER') %}
                                data-connected="true"
                                data-id="{{ app.user.id }}"
                            {% else %}
                                data-connected="false"
                            {% endif %}
                             data-admin="{% if is_granted('ROLE_ADMIN') %}true{% else %}false{% endif %}"
                             data-profile="{{ user.id }}"
                    >
                        <h3 class="text-white text-center mb-5">{{ 'message'|trans }}</h3>
                    </section>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if user is same as app.user %}
        {{ encore_entry_script_tags('new-message') }}
    {% endif %}
    {{ encore_entry_script_tags('profil-user') }}
    {% if is_granted('ROLE_ADMIN') %}
        {{ encore_entry_script_tags('delete-user') }}
    {% endif %}
{% endblock %}